// 回执式可靠粘贴(移植自 Handy paste_tx, 619 行全套机制)
// 核心: 剪贴板发布延迟供数据(lazy promise, declareTypes:owner:), 目标 app 读取时回调供数据=回执;
//       末次回执后 200ms 安静期才恢复原剪贴板; changeCount/ownership 守卫绝不覆盖用户新复制;
//       concealment markers 让剪贴板管理器跳过; 新事务先结算旧事务(flush_pending)。
// 线程模型(Handy 原样): 发布/chord 注入在主线程(promise 回调走主 runloop), 等待在 worker, settle hop 回主线程。
use std::sync::{Arc, Mutex};
use std::thread;
use std::time::{Duration, Instant};

use objc2::rc::Retained;
use objc2::{define_class, msg_send, AnyThread, DefinedClass};
use objc2_app_kit::{NSPasteboard, NSPasteboardTypeString};
use objc2_foundation::{NSArray, NSInteger, NSString};
use tauri::{AppHandle};
use tauri_plugin_clipboard_manager::ClipboardExt;

use crate::settings::Config;

/// 末次回执后的安静期(Chromium 类 app 会 probe-then-read 多次)
const QUIET_PERIOD: Duration = Duration::from_millis(200);
/// 转写文本占据剪贴板的硬上限(丢失键击时的失败模式=文本多留一会, 绝不贴旧内容)
const RESTORE_TIMEOUT: Duration = Duration::from_secs(8);
/// chord 注入失败: 无合法回执可能, 快速恢复
const FAILED_INJECTION_TIMEOUT: Duration = Duration::from_millis(500);

/// 第三方剪贴板管理器(Maccy/Paste)跳过本次内容的约定类型
const CONCEALMENT_TYPES: [&str; 3] = [
    "org.nspasteboard.TransientType",
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.AutoGeneratedType",
];

pub struct ProviderIvars {
    state: Arc<Mutex<TxState>>,
    text: String,
}

define_class!(
    #[unsafe(super(objc2_foundation::NSObject))]
    #[name = "VoiceMacPasteProvider"]
    #[ivars = ProviderIvars]
    pub struct PasteProvider;

    impl PasteProvider {
        // 读取回执: pasteboard 要求兑现承诺数据
        #[unsafe(method(pasteboard:provideDataForType:))]
        fn pasteboard_provide_data_for_type(&self, pasteboard: &NSPasteboard, data_type: &NSString) {
            let ivars = self.ivars();
            let is_text = unsafe { data_type.isEqualToString(NSPasteboardTypeString) };
            if is_text {
                if let Ok(mut state) = ivars.state.lock() {
                    state.record_receipt(Instant::now());
                }
            }
            let payload = if is_text {
                NSString::from_str(&ivars.text)
            } else {
                NSString::from_str("")
            };
            let _ = pasteboard.setString_forType(&payload, data_type);
        }

        #[unsafe(method(pasteboardChangedOwner:))]
        fn pasteboard_changed_owner(&self, _pasteboard: &NSPasteboard) {
            if let Ok(mut state) = self.ivars().state.lock() {
                state.ownership_lost = true;
            }
        }
    }
);

impl PasteProvider {
    fn new(state: Arc<Mutex<TxState>>, text: String) -> Retained<Self> {
        unsafe {
            let this = PasteProvider::alloc().set_ivars(ProviderIvars { state, text });
            msg_send![super(this), init]
        }
    }
}

/// 一次粘贴事务的共享状态(Handy TxState 原样)
#[derive(Debug)]
pub struct TxState {
    pub published_at: Instant,
    pub injected_at: Option<Instant>,
    pub injection_failed: bool,
    pub receipts: Vec<Instant>,
    pub ownership_lost: bool,
    pub cancelled: bool,
    pub logged_receipt: bool,
}

impl TxState {
    fn new() -> Self {
        Self {
            published_at: Instant::now(),
            injected_at: None,
            injection_failed: false,
            receipts: Vec::new(),
            ownership_lost: false,
            cancelled: false,
            logged_receipt: bool::default(),
        }
    }

    pub fn record_receipt(&mut self, at: Instant) {
        self.receipts.push(at);
        if !self.logged_receipt {
            if let Some(injected) = self.injected_at {
                if at >= injected {
                    self.logged_receipt = true;
                    crate::log::elog(&format!(
                        "[paste-tx] 目标读取回执: chord 后 {}ms",
                        at.duration_since(injected).as_millis()
                    ));
                }
            }
        }
    }

    fn last_receipt_after_injection(&self) -> Option<Instant> {
        let injected = self.injected_at?;
        self.receipts.iter().copied().rev().find(|t| *t >= injected)
    }

    pub fn any_receipt_after_injection(&self) -> bool {
        self.last_receipt_after_injection().is_some()
    }
}

enum WaitDecision {
    KeepWaiting,
    Finish,
}

fn evaluate(state: &TxState, now: Instant) -> WaitDecision {
    if state.ownership_lost || state.cancelled {
        return WaitDecision::Finish;
    }
    if let Some(last) = state.last_receipt_after_injection() {
        if now.duration_since(last) >= QUIET_PERIOD {
            return WaitDecision::Finish;
        }
    }
    let deadline = if state.injection_failed {
        FAILED_INJECTION_TIMEOUT
    } else {
        RESTORE_TIMEOUT
    };
    if now.duration_since(state.published_at) >= deadline {
        return WaitDecision::Finish;
    }
    WaitDecision::KeepWaiting
}

struct Pending {
    state: Arc<Mutex<TxState>>,
    saved_text: Option<String>,
    saved_image: Option<tauri::image::Image<'static>>,
    change_count: NSInteger,
    provider: Option<Retained<PasteProvider>>,
    auto_submit: bool,
    /// 追加回车次数(1..=10); 仅 auto_submit 为真时有效
    auto_submit_count: u32,
    /// restore_clipboard=false → 保留转写文本为普通文本(剪贴板管理器可记录)
    preserve_transcript: bool,
    transcript: String,
    settled: bool,
}

static PENDING: Mutex<Option<Arc<Mutex<Pending>>>> = Mutex::new(None);

/// 结算: 恰好一次; 回执确认后才发 auto-submit Enter; 守卫式恢复原剪贴板。必须主线程。
fn settle(pending: &Arc<Mutex<Pending>>, app_handle: &AppHandle) {
    let mut p = match pending.lock() {
        Ok(p) => p,
        Err(_) => return,
    };
    if p.settled {
        return;
    }
    p.settled = true;

    let (receipt_seen, ownership_lost) = match p.state.lock() {
        Ok(st) => (st.any_receipt_after_injection(), st.ownership_lost),
        Err(_) => (false, true),
    };

    // Enter 只在目标确实读到后发(防止提交旧内容); 次数由配置决定(1=换行, 2=空一行…)
    let enters = enter_count(p.auto_submit, p.auto_submit_count);
    if enters > 0 && receipt_seen {
        let _ = app_handle.run_on_main_thread(move || {
            for _ in 0..enters {
                let _ = crate::deliver::cg_key_tap(0x24, 0); // kVK_Return 无修饰
            }
        });
    }

    let still_ours = !ownership_lost
        && NSPasteboard::generalPasteboard().changeCount() == p.change_count;
    if !still_ours {
        crate::log::elog("[paste-tx] 剪贴板已被外部修改, 不动它");
    } else if p.preserve_transcript || !receipt_seen {
        // 审计B修复: 无回执(目标窗口可能不可输入)——保留转写文本供手动 CmdV,
        // 不恢复旧内容(否则用户手动粘贴拿到的是旧剪贴板, 体感"没复制")
        let _ = app_handle.clipboard().write_text(&p.transcript);
        crate::log::elog("[paste-tx] 无回执/保留模式: 转写文本保留在剪贴板");
    } else {
        let clipboard = app_handle.clipboard();
        if let Some(text) = &p.saved_text {
            let _ = clipboard.write_text(text);
        } else if let Some(image) = &p.saved_image {
            let _ = clipboard.write_image(image);
        } else {
            let _ = clipboard.clear();
        }
        crate::log::elog("[paste-tx] 原剪贴板已恢复(守卫通过)");
    }
    p.provider = None;
}

/// 新事务先结算旧事务(连续快速语音场景)
fn flush_pending(app_handle: &AppHandle) {
    let previous = match PENDING.lock() {
        Ok(mut slot) => slot.take(),
        Err(_) => None,
    };
    if let Some(previous) = previous {
        // 审计#3(对齐 Handy macos.rs:186): 调用方(reliable_paste)已在主线程,
        // 同步结算旧事务再快照——异步派发会让快照读到上一条的延迟供数据
        settle(&previous, app_handle);
    }
}

fn spawn_waiter(pending: Arc<Mutex<Pending>>, app_handle: AppHandle) {
    thread::spawn(move || {
        let outcome = loop {
            thread::sleep(Duration::from_millis(15));
            let result = {
                let p = match pending.lock() {
                    Ok(p) => p,
                    Err(_) => return,
                };
                if p.settled {
                    return;
                }
                let inner = match p.state.lock() {
                    Ok(st) => {
                        let now = Instant::now();
                        (evaluate(&st, now), st.any_receipt_after_injection())
                    }
                    Err(_) => return,
                };
                drop(p);
                inner
            };
            if let (WaitDecision::Finish, _) = result {
                break result.1;
            }
        };
        if outcome {
            crate::log::elog("[paste-tx] settle: 读取已安静");
        } else {
            crate::log::elog("[paste-tx] settle: 超时兜底恢复");
        }
        let pending_for_finish = pending.clone();
        let app_for_finish = app_handle.clone();
        let _ = app_handle.run_on_main_thread(move || {
            settle(&pending_for_finish, &app_for_finish);
            if let Ok(mut slot) = PENDING.lock() {
                let is_us = slot
                    .as_ref()
                    .map(|current| Arc::ptr_eq(current, &pending))
                    .unwrap_or(false);
                if is_us {
                    *slot = None;
                }
            }
        });
    });
}

/// 回执式粘贴入口(主线程调用)。Ok = 已发布+已注入, 恢复异步完成。
pub fn reliable_paste(text: &str, app_handle: &AppHandle, cfg: &Config) -> Result<(), String> {
    flush_pending(app_handle);

    let clipboard = app_handle.clipboard();
    let saved_text = clipboard.read_text().ok().filter(|t| !t.is_empty());
    let saved_image = if saved_text.is_none() {
        clipboard.read_image().ok().map(|image| image.to_owned())
    } else {
        None
    };

    let state = Arc::new(Mutex::new(TxState::new()));
    let provider = PasteProvider::new(state.clone(), text.to_string());
    let pasteboard = NSPasteboard::generalPasteboard();

    let mut types: Vec<Retained<NSString>> = Vec::with_capacity(1 + CONCEALMENT_TYPES.len());
    types.push(NSString::from_str("public.utf8-plain-text"));
    for t in CONCEALMENT_TYPES {
        types.push(NSString::from_str(t));
    }
    let types = NSArray::from_retained_slice(&types);
    let change_count: NSInteger =
        unsafe { msg_send![&*pasteboard, declareTypes: &*types, owner: &*provider] };
    if change_count <= 0 {
        return Err("declareTypes:owner: failed".to_string());
    }
    crate::log::elog(&format!("[paste-tx] 已发布延迟供数据(lazy promise)(changeCount {change_count})"));

    if let Ok(mut st) = state.lock() {
        st.injected_at = Some(Instant::now());
    }
    match crate::deliver::cg_key_tap(0x09, 1 << 20) {
        Ok(()) => crate::log::elog("[paste-tx] chord 已注入"),
        Err(e) => {
            if let Ok(mut st) = state.lock() {
                st.injection_failed = true;
            }
            crate::log::elog(&format!("[paste-tx] chord 注入失败: {e}"));
        }
    }

    let pending = Arc::new(Mutex::new(Pending {
        state,
        saved_text,
        saved_image,
        change_count,
        provider: Some(provider),
        auto_submit: cfg_auto_submit(cfg),
        auto_submit_count: cfg.auto_submit_count,
        preserve_transcript: !cfg.restore_clipboard,
        transcript: text.to_string(),
        settled: false,
    }));
    if let Ok(mut slot) = PENDING.lock() {
        *slot = Some(pending.clone());
    }
    spawn_waiter(pending, app_handle.clone());
    Ok(())
}

fn cfg_auto_submit(cfg: &Config) -> bool {
    cfg.auto_submit
}

/// 追加回车的次数：开关关闭 → 0（不追加）；开启 → 数量夹到 1..=10。
///
/// 上限 10 的理由：这是"每说一句就补 N 次回车"的全局行为，误配成很大的值会在每个输入框里刷屏；
/// 下限 1 的理由：开关已表达"不要回车"，开启状态下 0 与 1 同义，取 1 避免"开了却没反应"。
fn enter_count(enabled: bool, count: u32) -> u32 {
    if enabled {
        count.clamp(1, 10)
    } else {
        0
    }
}

#[cfg(test)]
mod tests {
    use super::enter_count;

    #[test]
    fn enter_count_rules() {
        assert_eq!(enter_count(false, 3), 0, "关闭时一律不追加");
        assert_eq!(enter_count(false, 0), 0);
        assert_eq!(enter_count(true, 0), 1, "开启时 0 与 1 同义");
        assert_eq!(enter_count(true, 1), 1);
        assert_eq!(enter_count(true, 2), 2);
        assert_eq!(enter_count(true, 99), 10, "上限 10");
    }
}
